nats.d.ts, package.json, src/connect.ts
added step to insure latest deps are pulled before bundling
updated client creation to point to the implementation
added PublishOptions to typescript interface
=> updated to latest nats-base-client dependencies

TODO.md, examples/bench.html, examples/bench.js, package.json, src/nats-base-client.ts, src/ws_transport.ts
- reworked benching to use built-in
- removed enqueue/dequeue of outbound
- added check on close that the websocket buffers are drained prior to closing.
=> bumped nats-base-client dependencies to v1.0.0-2

examples/bench.html, examples/bench.js, package.json, src/nats-base-client.ts, src/ws_transport.ts, test/helpers/launcher.js
- updated bench app
- updated nkeys dependency version
=> preparing for release

nats.d.ts, package.json
- [update] updated types definition to match nbc 1.0.0-13
=> updated ts definition file

examples/ngs.html
=> ngs connection sample

.gitignore, CODE-OF-CONDUCT.md, MAINTAINERS.md, README.md, bin/clone-nd.ts, examples/tls.conf, nats.d.ts, package-lock.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts, test/autounsub.js, test/basics.js, test/helpers/launcher.js
[update] updated nbc to rc2, fixing issue with default host port for websockets.
=> Transport config

README.md, nats.d.ts, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts, test/basics.js
[feat] supports `inboxPrefix` connection property
=> [update] nbc to 1.0.0-rc4

.github/workflows/natsws.yml
Fixed the gha ci script to declare the environment `CI` to get access to the secrets
=> fix reference of secret to enable test

.github/workflows/natsws.yml, nats.d.ts, package-lock.json, package.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts
- [update] nbc to v1.0.4 - for more information see release notes for https://github.com/nats-io/nats.deno/releases/tag/v1.0.4
=> release 1.1.2

.github/workflows/natsws.yml, nats.d.ts, package-lock.json, package.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts
[UPDATE] nbc to 1.0.8
[UPDATE] build/test dependencies
=> updated nbc, build and test dependencies

package-lock.json, package.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts
[UPDATE] nbc to 1.4.0
[UPDATE] build dependencies
=> preparing for 1.5.0

.github/workflows/natsws.yml, package-lock.json, package.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts, test/auth.js, test/autounsub.js, test/jetstream.js
[UPDATE] nbc to updated to v1.5.0
[UPDATE] use of deno to 1.17.x
[UPDATE] nats-server to 2.7.0
=> Release 1.6.0

README.md
details in https://github.com/nats-io/nats.ws/issues/125
=> nats import for 1.6+

package.json
=> [FIX] `main` in package.json

.github/workflows/natsws.yml, package.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts
[update] nbc library to 1.6.1, and nats-server to current version
=> preparing for release 1.7.2

package-lock.json, package.json, test/auth.js, test/jetstream.js
[TEST] added test verifying error reporting for an expired token https://github.com/nats-io/nats.deno/issues/268
[TEST] fixed test message verification to use regex
=> added test verifying fix under websocket

package-lock.json, package.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts, test/auth.js
[UPDATE] nbc to address transport.send() change
[CHANGE] updated transport to implement new transport.send()
=> [UPDATE] tranport.send()

src/ws_transport.ts
For those cannot use the simple WebSocket class constructor, this additional optional option allows one to create a WebSocket through other means. This is very helpful for platforms like Cloudflare Workers where one needs to use their APIs to create new WebSocket connections.
Docs: https://developers.cloudflare.com/workers/learning/using-websockets/#writing-a-websocket-client
=> Add Cloudflare compatiblity

.github/workflows/natsws.yml, package-lock.json, package.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts
[BUMP] nbc to point to main
[CI] bump nats-server, deno to current versions, and minor dev deps
=> dep updates

.github/workflows/natsws.yml, package-lock.json, package.json, src/connect.ts, src/mod.ts, src/nats-base-client.ts, src/ws_transport.ts, test/auth.js, test/autounsub.js, test/helpers/setup-browser-env.js, test/reconnect.js
[BUMP] nbc to 1.10.3, nats-server, deno, CI dependencies
=> [REL] 1.11.3

README.md
=> doc: added info on merging this project with nats.js
